export const signs = [
  {
    id: 0,
    title: "0",
    images:'./images/asl-0.jpg',
    link:"http://localhost:8000/run",
    
  },
  {
    id: 1,
    title: "1",
    images:'./images/asl-1.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 2,
    title: "2",
    images:'./images/asl-2.png',
    link:"http://localhost:8000/run",
  },
  {
    id: 3,
    title: "3",
    images:'./images/asl-3.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 4,
    title: "4",
    images:'./images/asl-4.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 5,
    title: "5",
    images:'./images/asl-5.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 6,
    title: "6",
    images:'./images/asl-6.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 7,
    title: "7",
    images:'./images/asl-7.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 8,
    title: "8",
    images:'./images/asl-8.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 9,
    title: "9",
    images:'./images/asl-9.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 10,
    title: "a",
    images:'./images/asl-a.png',
    link:"http://localhost:8000/run",
  },
  {
    id: 11,
    title: "b",
    images:'./images/asl-b.png',
    link:"http://localhost:8000/run",
  },
  {
    id: 12,
    title: "c",
    images:'./images/asl-c.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 13,
    title: "d",
    images:'./images/asl-d.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 14,
    title: "e",
    images:'./images/asl-e.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 15,
    title: "f",
    images:'./images/asl-f.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 16,
    title: "g",
    images:'./images/asl-g.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 17,
    title: "h",
    images:'./images/asl-h.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 18,
    title: "i",
    images:'./images/asl-i.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 19,
    title: "j",
    images:'./images/asl-j.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 20,
    title: "k",
    images:'./images/asl-k.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 21,
    title: "l",
    images:'./images/asl-l.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 22,
    title: "m",
    images:'./images/asl-m.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 23,
    title: "n",
    images:'./images/asl-n.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 24,
    title: "o",
    images:'./images/asl-o.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 25,
    title: "p",
    images:'./images/asl-p.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 26,
    title: "q",
    images:'./images/asl-q.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 27,
    title: "r",
    images:'./images/asl-r.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 28,
    title: "s",
    images:'./images/asl-s.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 29,
    title: "t",
    images:'./images/asl-t.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 30,
    title: "u",
    images:'./images/asl-u.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 31,
    title: "v",
    images:'./images/asl-v.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 32,
    title: "w",
    images:'./images/asl-w.png',
    link:"http://localhost:8000/run",
  },
  {
    id: 33,
    title: "x",
    images:'./images/asl-x.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 34,
    title: "y",
    images:'./images/asl-y.jpg',
    link:"http://localhost:8000/run",
  },
  {
    id: 35,
    title: "z",
    images:'./images/asl-z.png',
    link:"http://localhost:8000/run",
  }
  
];

